# fly.toml app configuration file generated for dark-wave-4173 on 2023-10-09T17:21:56-06:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "dark-wave-4173"
primary_region = "qro"
kill_signal = "SIGTERM"
swap_size_mb = 512

[mounts]
  source="stockprice_data"
  destination="/mnt/stockprice_data"

[build]

[deploy]

[env]
  DATABASE_PATH = "/mnt/stockprice_data/stockprices_chat.db"
  PHX_HOST = "dark-wave-4173.fly.dev"
  PORT = "8080"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
  [http_service.concurrency]
    type = "connections"
    hard_limit = 1000
    soft_limit = 1000
